#Use an official node runtime as a parent image
FROM node:22-alpine


#Set the working directory to /app
WORKDIR /app

#copy package.json and package-lock.json to the container
COPY package*.json ./

#Install any needed packages specified in package.json
RUN npm install

#Copy the rest of the application code to the container
COPY . .

#Make port 5000 available to the world outside this container
EXPOSE 5000

#Define commmand to run the app
CMD ["node", "./src/server.js"]